### ISSUE TITLE
could automatically call app.set('view engine', 'jade');

### ISSUE THREAD

**Issue by pocesar** [1602/jade-ext#6]
I know nothing is enforced, but if we are picking jade over ejs, it's expected to use jade all over, so since it's an adapter, could call `app.set('view engine', 'jade')` automatically, otherwise people can just `require('jade')` and do their thing

**Comment by 1602** [comment]
Nope, this is app-level configuration, and this is optional because you can use any view engine while it's view  file extension is the same as view engine name (as in express) without specifying engine
